# Nome que aparecerá no GitHub Actions
name: CI

# Define quais eventos disparam a pipeline
on:
  # Executa quando houver um push
  push:
    # Apenas para a branch main
    branches:
      - master

permissions: 
  id-token: write
  contents: read       

# Lista de jobs da pipeline
jobs:

  # Identificador do job
  build:

    # Nome exibido na interface do GitHub Actions
    name: "Build and Push"

    # Runner (máquina virtual) onde o job será executado
    runs-on: ubuntu-latest    

    # Sequência de etapas do job
    steps:

    # Faz checkout do código do repositório
    - uses: actions/checkout@v4

    # Nome amigável da etapa
    - name: Setup node

      # Action oficial para instalar o Node.js
      uses: actions/setup-node@v4

      # Configurações da action
      with:

        # Utiliza a versão do Node definida na matriz
        node-version: 24
        # Habilita cache das dependências do Yarn
        cache: 'yarn'      
      
    - run: yarn       
    - run: yarn run test       

    - name: Generate tag
      id: generate_tag
      run: | 
       SHA=$(echo $GITHUB_SHA | head -c7)
       echo "sha=$SHA" >> $GITHUB_OUTPUT  

    - name: Debug OIDC Token Subject
      run: |
        echo "Ref: ${{ github.ref }}"
        echo "Repository: ${{ github.repository }}"
        echo "Expected sub claim: repo:${{ github.repository }}:ref:${{ github.ref }}"   

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6.2.3
      with:   
        audience: sts.amazonaws.com     
        role-to-assume: 'arn:aws:iam::905418028782:role/ecr-role'
        aws-region: us-east-2

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build docker image 
      id: build-docker-image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        TAG: ${{ steps.generate_tag.outputs.sha }}
      run: |
       docker build -t $REGISTRY/devops-project:$TAG ./api
       docker push $REGISTRY/devops-project:$TAG  ./api
       IMAGE=${echo $REGISTRY/devops-project:$TAG}
       echo "image=$IMAGE" >> $GITHUB_OUTPUT

    - name: Deploy to ECR
      uses: awslabs/amazon-app-runner-deploy@main
      with:
        service: devops-project
        image: ${{ steps.build-docker-image.outputs.image }}
        access-role-arn: arn:aws:iam::905418028782:role/ecr-role
        region: us-east-2
        cpu: 1
        memory: 2
        port: 3000